### ISSUE TITLE
Doesn't seem to work with nvm

### ISSUE THREAD

**Issue by schottra** [Kikobeats/nodengine#1]
Running `nodengine` has no effect if the only node manager installed is NVM.  I did a little digging and I think it's because `which` doesn't work correctly on NVM, probably because of the way it installs itself as a shell function instead of just a symlink to an executable? (my linux/shell knowledge is a bit lacking)

**Comment by Kikobeats** [comment]
Actually I use `n` to switch node. Can you confirm that [nvm command to switch](https://github.com/Kikobeats/nodengine/blob/master/bin/index.js#L23) is correct?

On the other hand, try to run `which nvm` and paste what happens.

**Comment by spalger** [comment]
@Kikobeats the issue is that nvm is implemented as a [function](https://github.com/creationix/nvm/blob/master/nvm.sh#L1538), not an executable, so `which` isn't going to find anything

**Comment by Kikobeats** [comment]
I changed the algorithm; now is based in detect the npm package, but looks that nvm is not a npm package and it doesn't work too. Can you confirm?

**Comment by spalger** [comment]
Yeah, nvm isn't an npm package. There is a package called nvm, but it hasn't been updated in forever and isn't the canonical "nvm". That nvm is https://github.com/creationix/nvm

**Comment by spalger** [comment]
The internet is telling me that you can check for nvm like so:

``` sh
[ "$(type -t nvm)" == "function" ] && echo 'true'
```

**Comment by Kikobeats** [comment]
The problem is that doesn't exist when a exec process is created:

``` js
require('child_process').exec('nvm --version', function () {
  console.log(arguments)
})
```

``` bash
{ '0':
   { [Error: Command failed: nvm --version
   /bin/sh: nvm: command not found
   ] killed: false, code: 127, signal: null, cmd: 'nvm --version' },
  '1': '',
  '2': '/bin/sh: nvm: command not found\n' }
```

I tried to source the file first but doesn't work. what the hell.

**Comment by spalger** [comment]
Good point, this is how avn solved that issue: https://github.com/wbyoung/avn-nvm/blob/master/index.js#L20-L42

**Comment by Kikobeats** [comment]
@spalger I changed the implementation (v1.2.0) based in your comment. Can you confirme me that now nvm works fine? :-)

Notes that if you have `n` installed then it will use `n` instead of `nvm`.

**Comment by hasRandy** [comment]
@Kikobeats It does correctly find nvm now, but it doesn't install missing versions of node automatically.  If the required version is missing, it will just print out a message saying so (that's how the `nvm use` command works).

However, if you switch it to `nvm install`, it will attempt to install the specified version (skipping if it is already installed) and then switch to it afterwards.

**Comment by schottra** [comment]
@Kikobeats It does correctly find nvm now, but it doesn't install missing versions of node automatically. If the required version is missing, it will just print out a message saying so (that's how the nvm use command works).

However, if you switch it to nvm install, it will attempt to install the specified version (skipping if it is already installed) and then switch to it afterwards.

**Comment by Kikobeats** [comment]
Well, the intention of this package is switch between version.

In case of use `n`, It installs the version if is not present but this is a `n` effect based in the commander design.

I prefer don't handle install process: Just show you that is not present, so install and make it possible 😀.

**Comment by schottra** [comment]
@Kikobeats I suppose that makes sense. Maybe it could be a configuration option?  Honestly, the appeal of using nodengine was in automatically getting whatever version is required, and it seems a little strange that it behaves differently based on the switcher you use.  `n`'s docs say that it "installs and switches to" the desired version.  So the analogous command in `nvm` wouldn't be `use`, it would be `install`.  In fact, `n` has a `use` command that means something very different (temporarily switch to this node version and run the following command).

Worth thinking about.  I opened a PR for it, if you want to merge it, great.  Otherwise, feel free to close! :-)

**Comment by Kikobeats** [comment]
I bumped your PR in `v1.3.0` 🙌
