### ISSUE TITLE
question: defining function based on alias `cd'

### ISSUE THREAD

**Issue by rosskevin** [Kikobeats/nodengine#32]
I just updated everything on OSX, zsh is now 5.4.1_1 and I'm suddenly getting:

```
/Users/kross/.zshrc:127: defining function based on alias `cd'
/Users/kross/.zshrc:127: parse error near `()'
```

in my .zshrc on line

```
cd () { builtin cd "$@" && chpwd; }
```

I'm sure it is a local problem, but I know little about zsh scripting etc.  Any thoughts?

**Comment by Kikobeats** [comment]
I have the script inside `.extra:`:

```bash
chpwd () {
  local PKG=$PWD/package.json
  if [ -f "$PKG" ] && [ "$NODENGINE_LAST_DIR" != "$PWD" ]; then
    nodengine
    # printf "\033[36m%s\033[0m \033[90m%s\033[0m\n" "nodengine" "$(node --version)"
    NODENGINE_LAST_DIR=$PWD
  fi
}
```

**Comment by rosskevin** [comment]
I tried that, but it made no difference, same exact error.

**Comment by rosskevin** [comment]
This appears to be some kind of conflict with the latest `rvm`.  Another developer just performed all the latest updates (brew, rvm, ruby) and he encountered the same thing.  

I see rvm uses the same aliasing kind of mechanism.  I'm wondering if you cannot alias an alias...?

**Comment by Kikobeats** [comment]
oh man, rvm is a mistake. use n, seriously: https://www.npmjs.com/package/n

**Comment by rosskevin** [comment]
I use n for Node, rvm for Ruby.  n doesn't manage rubies.

**Comment by Kikobeats** [comment]
oh sorry, I understood `nvm`.

I have rvm as well:

```
rvm --version
rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
```

**Comment by rosskevin** [comment]
We are on `rvm 1.29.3` (latest stable)

**Comment by Kikobeats** [comment]
I close this because is not highly related with nodengine issue, but feel free to comment

**Comment by rosskevin** [comment]
Well, not sure what to say. It's an issue, verified on two machines with the recommended integration from the `README`.

So essentially, `nodengine` _doesn't work_ because it never gets triggered.  I agree this could be an environmental issue, but it could be more prevalent with others as we just did blanket brew/Ruby/rvm updates here.  

I actually expect others to start bumping into it.

**Comment by Kikobeats** [comment]
not sure why `rvm` is related with this.

If you execute `nodengine`, it works? 

Then is a problem related with your shell scripts

**Comment by rosskevin** [comment]
Yes, direct execution of `nodengine` has no problems.

The shell hooks are what makes `nodengine` useful in my opinion.  Otherwise I'm more likely to just type `n + arrow + return` instead of `nodengine` when I change directories.

Also, these same scripts have been working for at least a year, the ones copied from the README _here_.  So agreed, environmental change, but the scripts from _here_ are the only things breaking with updated software.

**Comment by rosskevin** [comment]
Finally I found it. I knew it!  Error prone syntax, so this is officially a bug.  Credit to https://github.com/robbyrussell/oh-my-zsh/issues/6237#issuecomment-321990168

I'll PR the readme change that works.
