### ISSUE TITLE
question: autoswitching when `cd` to dir

### ISSUE THREAD

**Issue by rosskevin** [Kikobeats/nodengine#7]
I'm not sure how the rubymine terminal window differs from my OSX console, but I've never had a problem/difference with RVM etc.  I use bash/nvm and auto switching is working fine from the osx console.

``` bash
kross:real-world kross$ node --version
bash: node: command not found
kross:real-world kross$ nvm --version
0.31.0
kross:real-world kross$ nvm list
         v6.1.0
default -> 5 (-> N/A)
node -> stable (-> v6.1.0) (default)
stable -> 6.1 (-> v6.1.0) (default)
iojs -> N/A (default)
```

What info can I provide to help get this working here?  I'm happy to PR if you can point me in the right direction.

**Comment by Kikobeats** [comment]
nvm use [this command](https://github.com/Kikobeats/nodengine/blob/master/bin/switcher.js#L9) for do version switch.

Also node version need to be declared in the `package.json` to do the switch. Are you sure that node version in `package.json` is present?

**Comment by rosskevin** [comment]
package.json was:

``` javascript
"engines" : { "node" : ">=6" }
```

I was effectively running:

``` bash
$ bash -c 'source $NVM_DIR/nvm.sh; nvm install >=6'
No .nvmrc file found

Node Version Manager

Note: <version> refers to any version-like string nvm understands. This includes:
  - full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)
  - default (built-in) aliases: node, stable, unstable, iojs, system
  - custom aliases you define with `nvm alias foo`
```

Which couldn't have worked anyway.  

I have messed up my OSX terminal switcher, investigating now.  I'll close this shortly once I confirm it works.

**Comment by rosskevin** [comment]
I screwed up my original env by deleting my default node 5.  

I'm in OSX terminal, and expecting the end result here to be an auto-switch to 6.  This is a fresh 5 install:

``` bash
kross:~ kross$ node -v
v5.11.1
kross:~ kross$ npm install nodengine --global --production
/Users/kross/.nvm/versions/node/v5.11.1/bin/nodengine -> /Users/kross/.nvm/versions/node/v5.11.1/lib/node_modules/nodengine/bin/index.js
/Users/kross/.nvm/versions/node/v5.11.1/lib
└── nodengine@1.3.1 

kross:~ kross$ node -v
v5.11.1
kross:~ kross$ nvm list
->      v5.11.1
         v6.1.0
default -> 5 (-> v5.11.1)
node -> stable (-> v6.1.0) (default)
stable -> 6.1 (-> v6.1.0) (default)
iojs -> N/A (default)
kross:~ kross$ cat projects/af_core/package.json | grep engines
  "engines" : { "node" : "6" }
kross:~ kross$ cd projects/af_core/
kross:af_core kross$ node -v
v5.11.1
```

I had this working before, so clearly a user error, but I'm not spotting it.

BTW - this is working, so it seems that `nodeengine` isn't seeing my switch into the dir:

``` bash
kross:af_core kross$ bash -c 'source $NVM_DIR/nvm.sh; nvm install 6'
v6.1.0 is already installed.
Now using node v6.1.0 (npm v3.8.6)
```

**Comment by Kikobeats** [comment]
Then I don't know if a problem related with windows, or need to change the command used to switch the version using nvm?

**Comment by rosskevin** [comment]
It's OSX, not windows.  `nvm use` works fine, each time I run the command you pointed at, no problem.  I don't think it is getting triggered.  Can I turn on any verbose logging in `nodeengine`? even by editing the file?

**Comment by Kikobeats** [comment]
try:
- git clone `https://github.com/Kikobeats/nodengine`
- run local the package with `npm link nodengine`
- now use `nodengine` to switch version in a fake project and insert console.log inside nodengine/bin/index.js on interesting points.

Actually I'm using `n` for switching, it's more simple :/

**Comment by Kikobeats** [comment]
Maybe @schottra @spalger can help here!

**Comment by rosskevin** [comment]
Ok, **huge** misunderstanding on my part.

I expected it to work like `rvm`, when you `cd` into a dir, I expected it to run `nodengine` and pick the right node, without me actually running the command.

Were you considering hooking into the shell like this?

**Comment by Kikobeats** [comment]
I'm happy to convert this from bug into question 😛

For automatic switching, check docs:

> For automatic switching and avoid type the command manually, just add this snippet into .extra:

```
echo "\nchpwd () {\n nodengine\n}" >> ~/.extra
```

**Comment by rosskevin** [comment]
@Kikobeats - setting up the `chpwd` in `~/.extra` doesn't work in bash shell, I also tried adding to `.bash_profile`.

Is `.extra` a zsh thing?

**Comment by Kikobeats** [comment]
@rosskevin it could be possible, I'm not sure and I don't found relevant information about that. btw, `.bash_profile` is a good place too.

**Comment by rosskevin** [comment]
Got it, I'll add it to the PR for readme.
